server:
  context-path: /
  port: 8190

spring:
  redis:
    mode: single
    #通用配置
    host: 127.0.0.1:7000
    #数据库X号
    database: 10
    password:
    # 跨集群执行命令时最大重定向数量
    max-redirects: 5
    # 连接超时时间（毫秒）
    timeout: 3000
    #连接池配置
    # 连接池中的最大空闲连接
    pool.max-idle: 16
    # 连接池中的最小空闲连接
    pool.min-idle: 8
    # 连接池最大连接数（使用负值表示没有限制）
    pool.max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    pool.max-wait: 3000
    # 连接池连接最大超时时间
    pool.conn-timeout: 3000
    # 空闲连接连接超时时间
    pool.so-timeout: 3000
    # 连接池大小
    pool.size: 10
    #单机配置
    single:
      address: 127.0.0.1:7000

    #集群配置
    cluster.scan-interval: 1000
    cluster.nodes:  127.0.0.1:7000
    cluster.read-mode: SLAVE
    cluster.retry-attempts: 3
    cluster.failed-attempts: 3
    cluster.slave-connection-pool-size: 64
    cluster.master-connection-pool-size: 64
    cluster.retry-interval: 1500

    #哨兵配置
    sentinel.master: business-maste
    sentinel.nodes: 127.0.0.1:6379
    sentinel.master-onlyWrite: true
    sentinel.fail-max: 3

#spring:
#  redis:
#    #默认选择0数据库
#    database: 10
#    host: 127.0.0.1:6379
#    password:
#    #port: 6379
#    # 跨集群执行命令时最大重定向数量
#    max-redirects: 5
#
#    jedis:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 100
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: 6000
#        # 连接池中的最大空闲连接
#        max-idle: 100
#        # 连接池中的最小空闲连接
#        min-idle: 0
#    # 连接超时时间（毫秒）
#    timeout: 30000